"""Keccak-f[1600] reference implementation with full per-step tracing.

Pure Python + NumPy.  No GUI, no hashlib.

State model
-----------
The Keccak state is 5 x 5 x 64 bits.  We keep it as a NumPy ``uint64`` array
of shape ``(5, 5)`` indexed ``[x, y]``; bit ``z`` of ``A[x, y]`` is the state
bit ``a[x][y][z]`` of the specification (FIPS 202, section 3.1).  All step
mappings accept an optional leading batch dimension, i.e. arrays of shape
``(N, 5, 5)``, so N independent permutations can run in lock-step - this is
exactly the "batched lanes" SIMD layout the visualizer shows.

Vocabulary (FIPS 202, figure 2):

* lane   - the 64 bits ``a[x][y][*]``
* row    - the 5 bits ``a[*][y][z]``
* column - the 5 bits ``a[x][*][z]``
* slice  - the 25 bits ``a[*][*][z]``
* plane  - the 320 bits ``a[*][y][*]``
* sheet  - the 320 bits ``a[x][*][*]``

The five step mappings are exposed as separate functions (``theta``, ``rho``,
``pi``, ``chi``, ``iota``) and ``permute`` chains them, recording a snapshot
after every step when asked to.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, List, Optional, Tuple

import numpy as np

# --------------------------------------------------------------------------
# Constants, exposed as data
# --------------------------------------------------------------------------

LANE_BITS = 64
STATE_BYTES = 200
STATE_BITS = 1600
NUM_ROUNDS = 24
MASK64 = np.uint64(0xFFFFFFFFFFFFFFFF)

STEP_NAMES: Tuple[str, ...] = ("theta", "rho", "pi", "chi", "iota")
STEP_SYMBOLS = {"theta": "θ", "rho": "ρ", "pi": "π", "chi": "χ", "iota": "ι", "load": "⇥", "initial": "·"}


def _lfsr_rc_bit(t: int) -> int:
    """rc(t) from FIPS 202 algorithm 5: an 8-bit LFSR with polynomial
    x^8 + x^6 + x^5 + x^4 + 1, returning its output bit."""
    if t % 255 == 0:
        return 1
    r = 1
    for _ in range(1, t % 255 + 1):
        r <<= 1
        if r & 0x100:
            r ^= 0x171  # x^8 + x^6 + x^5 + x^4 + 1
        r &= 0xFF
    return r & 1


def compute_round_constants(num_rounds: int = 24) -> List[int]:
    """Round constants RC[ir] for ir in 0..num_rounds-1 (FIPS 202 alg. 6).

    Bit ``2^j - 1`` of RC[ir] is rc(j + 7*ir) for j in 0..6."""
    rcs = []
    for ir in range(num_rounds):
        rc = 0
        for j in range(7):
            if _lfsr_rc_bit(j + 7 * ir):
                rc |= 1 << ((1 << j) - 1)
        rcs.append(rc)
    return rcs


def compute_rho_offsets() -> np.ndarray:
    """The rho rotation offset table r[x][y] (FIPS 202 algorithm 2).

    Generated by walking (x, y) -> (y, 2x + 3y) from (1, 0); the t-th
    position gets offset (t+1)(t+2)/2 mod 64 - a triangular number."""
    r = np.zeros((5, 5), dtype=np.int64)
    x, y = 1, 0
    for t in range(24):
        r[x, y] = ((t + 1) * (t + 2) // 2) % 64
        x, y = y, (2 * x + 3 * y) % 5
    return r


#: RC[ir], ir = 0..23, derived from the LFSR rather than typed in.
ROUND_CONSTANTS: List[int] = compute_round_constants(NUM_ROUNDS)

#: rho offsets, indexed [x, y].
RHO_OFFSETS: np.ndarray = compute_rho_offsets()
RHO_OFFSETS.setflags(write=False)

# Cross-check against the well-known tabulated values (FIPS 202 table 2).
_EXPECTED_RHO = np.array(
    [
        [0, 36, 3, 41, 18],
        [1, 44, 10, 45, 2],
        [62, 6, 43, 15, 61],
        [28, 55, 25, 21, 56],
        [27, 20, 39, 8, 14],
    ]
)
assert np.array_equal(RHO_OFFSETS, _EXPECTED_RHO), "rho table derivation broken"
assert ROUND_CONSTANTS[0] == 0x0000000000000001
assert ROUND_CONSTANTS[23] == 0x8000000080008008

# pi:  A'[x, y] = A[(x + 3y) mod 5, x]   (FIPS 202 algorithm 3)
_XI, _YI = np.meshgrid(np.arange(5), np.arange(5), indexing="ij")
PI_SOURCE_X: np.ndarray = (_XI + 3 * _YI) % 5
PI_SOURCE_Y: np.ndarray = _XI.copy()
PI_SOURCE_X.setflags(write=False)
PI_SOURCE_Y.setflags(write=False)


def pi_target(x: int, y: int) -> Tuple[int, int]:
    """Where lane (x, y) moves to under pi: (y, 2x + 3y)."""
    return y % 5, (2 * x + 3 * y) % 5


def pi_source(x: int, y: int) -> Tuple[int, int]:
    """Which lane lands on (x, y) under pi: ((x + 3y) mod 5, x)."""
    return (x + 3 * y) % 5, x % 5


# --------------------------------------------------------------------------
# Lane helpers
# --------------------------------------------------------------------------

_R64 = RHO_OFFSETS.astype(np.uint64)
_R64_INV = np.where(RHO_OFFSETS == 0, 0, 64 - RHO_OFFSETS).astype(np.uint64)
_R64_IS_ZERO = RHO_OFFSETS == 0


def rol64(lanes: np.ndarray, n) -> np.ndarray:
    """Rotate uint64 lanes left by ``n`` bits (scalar or broadcastable array)."""
    n = np.asarray(n, dtype=np.int64) % 64
    n_u = n.astype(np.uint64)
    inv = np.where(n == 0, 0, 64 - n).astype(np.uint64)
    rolled = (lanes << n_u) | (lanes >> inv)
    return np.where(n == 0, lanes, rolled).astype(np.uint64)


def new_state() -> np.ndarray:
    return np.zeros((5, 5), dtype=np.uint64)


def state_from_bytes(data: bytes) -> np.ndarray:
    """200 bytes -> (5, 5) lanes.  Lane (x, y) occupies bytes 8*(x+5y).., LE."""
    if len(data) != STATE_BYTES:
        raise ValueError("state must be exactly 200 bytes")
    lanes = np.frombuffer(data, dtype="<u8").astype(np.uint64)  # index x + 5y
    return lanes.reshape(5, 5).T.copy()  # [y, x] -> [x, y]


def state_to_bytes(state: np.ndarray) -> bytes:
    return np.ascontiguousarray(state.T, dtype="<u8").tobytes()


def lanes_to_bits(state: np.ndarray) -> np.ndarray:
    """(…, 5, 5) uint64 -> (…, 5, 5, 64) uint8 array of bits, bit z at [.., z]."""
    shifts = np.arange(64, dtype=np.uint64)
    return ((state[..., None] >> shifts) & np.uint64(1)).astype(np.uint8)


def bits_to_lanes(bits: np.ndarray) -> np.ndarray:
    weights = (np.uint64(1) << np.arange(64, dtype=np.uint64))
    return np.bitwise_or.reduce(bits.astype(np.uint64) * weights, axis=-1).astype(np.uint64)


def state_to_flat_bits(state: np.ndarray) -> np.ndarray:
    """1600-entry bit vector in the standard bit-string order: index 64*(x+5y)+z."""
    return lanes_to_bits(state).transpose(1, 0, 2).reshape(-1)


def flat_bits_to_state(bits: np.ndarray) -> np.ndarray:
    return bits_to_lanes(np.asarray(bits).reshape(5, 5, 64).transpose(1, 0, 2))


def hamming_weight(state: np.ndarray) -> int:
    return int(lanes_to_bits(state).sum())


def lane_index(x: int, y: int) -> int:
    """Lane number in the byte/bit-string order: x + 5y."""
    return x + 5 * y


def bit_index(x: int, y: int, z: int) -> int:
    return 64 * lane_index(x, y) + z


def bit_coords(i: int) -> Tuple[int, int, int]:
    lane, z = divmod(i, 64)
    y, x = divmod(lane, 5)
    return x, y, z


# --------------------------------------------------------------------------
# Step mappings.  All accept (..., 5, 5) arrays and return new arrays.
# --------------------------------------------------------------------------


def theta_parts(a: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return (A', C, D) for the theta step.

    C[x]    = A[x,0] ^ A[x,1] ^ A[x,2] ^ A[x,3] ^ A[x,4]   (column parities)
    D[x]    = C[x-1] ^ ROT(C[x+1], 1)
    A'[x,y] = A[x,y] ^ D[x]
    """
    c = np.bitwise_xor.reduce(a, axis=-1)  # (..., 5) parity of sheet x
    d = np.roll(c, 1, axis=-1) ^ rol64(np.roll(c, -1, axis=-1), 1)
    return a ^ d[..., :, None], c, d


def theta(a: np.ndarray) -> np.ndarray:
    return theta_parts(a)[0]


def rho(a: np.ndarray) -> np.ndarray:
    """A'[x,y] = ROT(A[x,y], r[x,y])."""
    rolled = (a << _R64) | (a >> _R64_INV)
    return np.where(_R64_IS_ZERO, a, rolled).astype(np.uint64)


def pi(a: np.ndarray) -> np.ndarray:
    """A'[x,y] = A[(x+3y) mod 5, x]   i.e. lane (x,y) moves to (y, 2x+3y)."""
    return a[..., PI_SOURCE_X, PI_SOURCE_Y]


def chi(a: np.ndarray) -> np.ndarray:
    """A'[x,y] = A[x,y] ^ (~A[x+1,y] & A[x+2,y])  - the only nonlinear step."""
    return a ^ (~np.roll(a, -1, axis=-2) & np.roll(a, -2, axis=-2))


def iota(a: np.ndarray, round_index: int) -> np.ndarray:
    out = a.copy()
    out[..., 0, 0] ^= np.uint64(ROUND_CONSTANTS[round_index])
    return out


STEP_FUNCS = {"theta": theta, "rho": rho, "pi": pi, "chi": chi, "iota": iota}


# --------------------------------------------------------------------------
# Trace
# --------------------------------------------------------------------------


@dataclass
class Snapshot:
    """State after one step mapping (or the initial state, index 0)."""

    index: int  # 0 = initial; then 1 + 5*round + step
    round: int  # -1 for the initial state
    step: str  # "initial" or one of STEP_NAMES
    state: np.ndarray  # (5, 5) uint64
    skipped: bool = False  # step was disabled via step toggles
    theta_c: Optional[np.ndarray] = None  # (5,) column parities, theta only
    theta_d: Optional[np.ndarray] = None  # (5,) correction lanes, theta only
    round_constant: Optional[int] = None  # iota only
    round_index_abs: Optional[int] = None  # index into ROUND_CONSTANTS
    info: Optional[dict] = None  # extra data for non-permutation snapshots (e.g. loading)

    @property
    def label(self) -> str:
        if self.step == "initial":
            return "initial"
        if self.step == "load":
            return f"load cycle {self.info.get('cycle', 0)}" if self.info else "load"
        return f"round {self.round} {STEP_SYMBOLS[self.step]} ({self.step})"


@dataclass
class Trace:
    """Complete record of one Keccak-p permutation call."""

    snapshots: List[Snapshot] = field(default_factory=list)
    num_rounds: int = NUM_ROUNDS
    enabled_steps: Tuple[str, ...] = STEP_NAMES
    round_offset: int = 0  # first absolute round index used

    def __len__(self) -> int:
        return len(self.snapshots)

    def __getitem__(self, i: int) -> Snapshot:
        return self.snapshots[i]

    @property
    def initial(self) -> np.ndarray:
        return self.snapshots[0].state

    @property
    def final(self) -> np.ndarray:
        return self.snapshots[-1].state

    def index_of(self, round_: int, step: str) -> int:
        return 1 + 5 * round_ + STEP_NAMES.index(step)

    def round_end_indices(self) -> List[int]:
        return [self.index_of(r, "iota") for r in range(self.num_rounds)]


def permute(
    state: np.ndarray,
    num_rounds: int = NUM_ROUNDS,
    trace: bool = False,
    enabled_steps: Iterable[str] = STEP_NAMES,
    round_offset: Optional[int] = None,
):
    """Keccak-p[1600, num_rounds].

    Returns the new state, or ``(new_state, Trace)`` when ``trace`` is True.

    ``num_rounds`` < 24 follows FIPS 202 section 3.4: the rounds used are the
    *last* ``num_rounds`` of the 24 (round constants RC[24-nr .. 23]).  Pass
    ``round_offset=0`` to use RC[0 ..] instead.

    ``enabled_steps`` lets individual step mappings be switched off (for
    teaching what each one contributes).  A disabled step still produces a
    snapshot, flagged ``skipped``, so trace indices stay uniform.
    """
    if not 1 <= num_rounds <= NUM_ROUNDS:
        raise ValueError("num_rounds must be in 1..24")
    enabled = tuple(s for s in STEP_NAMES if s in set(enabled_steps))
    if round_offset is None:
        round_offset = NUM_ROUNDS - num_rounds
    a = np.array(state, dtype=np.uint64, copy=True)
    tr = Trace(num_rounds=num_rounds, enabled_steps=enabled, round_offset=round_offset)
    if trace:
        tr.snapshots.append(Snapshot(0, -1, "initial", a.copy()))

    for r in range(num_rounds):
        ir = round_offset + r
        for si, name in enumerate(STEP_NAMES):
            c = d = None
            skipped = name not in enabled
            if not skipped:
                if name == "theta":
                    a, c, d = theta_parts(a)
                elif name == "iota":
                    a = iota(a, ir)
                else:
                    a = STEP_FUNCS[name](a)
            if trace:
                tr.snapshots.append(
                    Snapshot(
                        index=1 + 5 * r + si,
                        round=r,
                        step=name,
                        state=a.copy(),
                        skipped=skipped,
                        theta_c=None if c is None else c.copy(),
                        theta_d=None if d is None else d.copy(),
                        round_constant=ROUND_CONSTANTS[ir] if name == "iota" else None,
                        round_index_abs=ir,
                    )
                )
    if trace:
        return a, tr
    return a


def keccak_f1600(state: np.ndarray) -> np.ndarray:
    """Plain Keccak-f[1600] (24 rounds, no trace)."""
    return permute(state)


# --------------------------------------------------------------------------
# Per-cell influence relations (used by the UI's "what feeds this cell")
# --------------------------------------------------------------------------

Cell = Tuple[int, int, int]


def sources_of(step: str, x: int, y: int, z: int) -> List[Cell]:
    """Cells of the *input* state that determine output cell (x, y, z) of ``step``."""
    if step == "theta":
        cells = [(x, y, z)]
        cells += [((x - 1) % 5, yy, z) for yy in range(5)]  # C[x-1] at z
        cells += [((x + 1) % 5, yy, (z - 1) % 64) for yy in range(5)]  # C[x+1] rotated by 1
        return cells
    if step == "rho":
        return [(x, y, (z - int(RHO_OFFSETS[x, y])) % 64)]
    if step == "pi":
        sx, sy = pi_source(x, y)
        return [(sx, sy, z)]
    if step == "chi":
        return [(x, y, z), ((x + 1) % 5, y, z), ((x + 2) % 5, y, z)]
    if step == "iota":
        return [(x, y, z)]
    raise ValueError(step)


def targets_of(step: str, x: int, y: int, z: int) -> List[Cell]:
    """Cells of the *output* state that input cell (x, y, z) of ``step`` influences."""
    if step == "theta":
        cells = [(x, y, z)]
        cells += [((x + 1) % 5, yy, z) for yy in range(5)]  # I am in C[x] = C[(x+1)-1]
        cells += [((x - 1) % 5, yy, (z + 1) % 64) for yy in range(5)]  # I am in C[x] = C[(x-1)+1], rotated
        return cells
    if step == "rho":
        return [(x, y, (z + int(RHO_OFFSETS[x, y])) % 64)]
    if step == "pi":
        tx, ty = pi_target(x, y)
        return [(tx, ty, z)]
    if step == "chi":
        return [(x, y, z), ((x - 1) % 5, y, z), ((x - 2) % 5, y, z)]
    if step == "iota":
        return [(x, y, z)]
    raise ValueError(step)


def move_cell(step: str, x: int, y: int, z: int) -> Cell:
    """Where the *bit sitting at* (x, y, z) is after ``step``.  Only rho and
    pi move bits; the other steps leave positions alone (and may flip values)."""
    if step == "rho":
        return x, y, (z + int(RHO_OFFSETS[x, y])) % 64
    if step == "pi":
        tx, ty = pi_target(x, y)
        return tx, ty, z
    return x, y, z


def step_description(step: str) -> str:
    return {
        "theta": "A[x,y] ^= C[x-1] ^ ROT(C[x+1], 1)   where C[x] = parity of column x",
        "rho": "A[x,y] = ROT(A[x,y], r[x,y])",
        "pi": "A[y, 2x+3y] = A[x, y]",
        "chi": "A[x,y] ^= ~A[x+1,y] & A[x+2,y]",
        "iota": "A[0,0] ^= RC[ir]",
        "load": "state[word] ^= bus_word   (rate part only)",
        "initial": "block loaded; permutation starts",
    }[step]


__all__ = [
    "LANE_BITS",
    "STATE_BYTES",
    "STATE_BITS",
    "NUM_ROUNDS",
    "STEP_NAMES",
    "STEP_SYMBOLS",
    "ROUND_CONSTANTS",
    "RHO_OFFSETS",
    "PI_SOURCE_X",
    "PI_SOURCE_Y",
    "compute_round_constants",
    "compute_rho_offsets",
    "pi_target",
    "pi_source",
    "rol64",
    "new_state",
    "state_from_bytes",
    "state_to_bytes",
    "lanes_to_bits",
    "bits_to_lanes",
    "state_to_flat_bits",
    "flat_bits_to_state",
    "hamming_weight",
    "lane_index",
    "bit_index",
    "bit_coords",
    "theta",
    "theta_parts",
    "rho",
    "pi",
    "chi",
    "iota",
    "STEP_FUNCS",
    "Snapshot",
    "Trace",
    "permute",
    "keccak_f1600",
    "sources_of",
    "targets_of",
    "move_cell",
    "step_description",
]
